version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=e_commerce_test_task_production
      - POSTGRES_USER=e_commerce_test_task
      - POSTGRES_PASSWORD=e_commerce_test_task
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  server:
    build:
      context: ./server
    ports:
      - 3000:3000
    restart: always
    environment:
      - SECRET_KEY_BASE=secret-key
      - POSTGRES_USER=e_commerce_test_task
      - POSTGRES_PASSWORD=e_commerce_test_task
    depends_on:
      - db
    volumes:
      - staticfiles:/backend/staticfiles
  nginx:
    build:
      context: .
      dockerfile: ./webserver/Dockerfile
    restart: always
    volumes:
      - staticfiles:/staticfiles
    ports:
      - 80:80
    depends_on:
      - server
volumes:
  staticfiles:
  postgres_data:
