version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    env_file:
      - /postgres/.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile.dev
    expose:
      - 3000
    restart: unless-stopped
    env_file:
      - /server/.env
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - staticfiles:/server/staticfiles
    depends_on:
      - db
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./webserver/Dockerfile
    restart: unless-stopped
    volumes:
      - staticfiles:/staticfiles
    ports:
      - 80:80
    depends_on:
      - server

volumes:
  staticfiles:
  postgres_data:
