version: "3.9"

services:
  db:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: unless-stopped
    env_file:
      - /postgres/.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  server:
    container_name: rails-development-server
    build:
      context: ./server
      dockerfile: ./Dockerfile.dev
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    restart: unless-stopped
    env_file:
      - /server/.env
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - ./server:/server:cached
      - bundle-volume:/usr/local/bundle
    depends_on:
      - db
  client:
    container_name: vite-development-server
    build:
      context: ./client
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./client/src:/client/src
    depends_on:
      - server

volumes:
  bundle-volume:
  postgres_data:
